Repository purnima143/Kurakoo, pull requests merged in 2021-03, with the labels that each got.

#27 added issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/pull_request_template.md
Labels: gssoc21, level1

#20 feat(#15): Setup response handler for the API
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/package-lock.json~a81d46041e3e8a1443d3fd7b0d128f686f9c4356
  server/.gitignore
  server/package-lock.json
  server/src/helpers/responseHandler.ts
  server/src/routes/root.ts
Labels: gssoc21, level2

#42 Create Sign Up page - Issue 19
  client/package-lock.json
  client/package.json
  client/public/images/Formimage.png
  client/public/images/kurakoo-logo.png
  client/src/App.js
  client/src/Component/SignUp/SignUp.css
  client/src/Component/SignUp/SignUp.js
Labels: frontend, gssoc21, level2

#46 Removed bugs from backend
  server/.env_sample
  server/src/controller/interfaces.js
  server/src/index.js
  server/src/index.ts
  server/src/middleware/logger.js
  server/src/middleware/logger.ts
  server/src/models/example.model.js
  server/src/routes/api.js
  server/src/routes/api.ts
  server/src/routes/notFound.js
  server/src/routes/notFound.ts
  server/src/routes/root.js
  server/src/routes/root.ts
  server/src/types/interfaces.ts
Labels: backend, bug, gssoc21, level2

#64 Navbar & header done in Feed Page
  client/public/images/Group_4.png
  client/public/images/Group_5.png
  client/public/images/logo.png
  client/public/images/logo512.png
  client/public/images/profile_pic.jpg
  client/src/App.js
  client/src/Component/feedpage/FeedPage.css
  client/src/Component/feedpage/FeedPage.js
  client/src/Component/navbar/NavBar.css
  client/src/Component/navbar/Navbar.js
  client/src/Component/searchbar/SearchBar.css
  client/src/Component/searchbar/SearchBar.js
  package-lock.json
Labels: frontend, gssoc21, level2

#82 Adding the images of Homepage created in Figma
  assets/Kurakoo HomePage1.PNG
  assets/Kurakoo HomePage2.PNG
Labels: design, gssoc21, level2

#78 Setup Guidelines
  README.md
  client/README.md
Labels: documentation, gssoc21, level1

#81 Question Page designing
  assets/Post question.png
  assets/Question page.png
Labels: design, gssoc21, level2, ui/ux

#72 Issue 21 : Created Feed Page
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/dummyData.js
  client/src/components/feed.css
  client/src/components/feed.js
  client/src/components/feedComponent.css
  client/src/components/feedComponent.js
  client/src/components/imgAvatar.png
  client/src/components/img_avatar.png
  client/src/components/img_avatar2.png
  client/src/components/kurakoo-logo.png
Labels: frontend, gssoc21, level2

#77 Added Signup api
  server/.env.example
  server/package.json
  server/src/controllers/auth.controller.js
  server/src/helpers/responseHandler.js
  server/src/index.js
  server/src/models/example.model.js
  server/src/models/user.model.js
  server/src/routes/auth.routes.js
  server/src/routes/root.js
  server/src/validators/auth.validator.js
Labels: Level3, backend, gssoc21

#99 Changed description of the project in pacakage.json
  server/package.json
Labels: bug, gssoc21, level1

#94 Designs for Home Page and Profile Page (#5) (#6)
  assets/Home Page - Feed Page.png
  assets/Notifications Page.png
  assets/Profile of Others.png
  assets/Profiles with Hover Animations.png
  assets/Your Profile.png
Labels: design, gssoc21, level2

#84 Added the image of profile page created in Figma
  assets/Profile Page1.png
Labels: design, gssoc21, level2

#80 code of conduct added
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc21, level1

#93 added favicon and fixed SignIn issue
  client/public/images/favicon.png
  client/public/index.html
  client/src/Component/SignIn/SignIn.js
  client/src/Component/SignUp/SignUp.js
Labels: bug, frontend, gssoc21, level2

#104 Update README.md
  README.md
Labels: documentation, gssoc21, level0

#114 error handling while connecting to a database
  client/src/Component/SignIn/SignIn.js
  client/src/Component/SignUp/SignUp.js
  server/package.json
  server/src/index.js
Labels: gssoc21, level2

#127 Image of feed page made by me
  assets/Feed_page.png
Labels: design, gssoc21, level2

#133 added meta http-equiv attribute which provides the http header to the…
  client/public/index.html
Labels: gssoc21, level2

#138 The signup button is made visible!
  client/src/Component/homepage/homepage.css
Labels: gssoc21, level2

#135 added concurrently
  .gitignore
  README.md
  package-lock.json
  package.json
  server/package.json
Labels: Level3, gssoc21

#139 Concurrently bug fixed
  README.md
  package.json
Labels: gssoc21, level2

#123 Added code for the Signin
  server/src/common-middleware/middleware.js
  server/src/controllers/auth.controller.js
  server/src/routes/auth.routes.js
  server/src/routes/root.js
  server/src/validators/auth.validator.js
Labels: Level3, gssoc21

#141 Replace body-parser with express inbuilt functions
  server/src/index.js
Labels: gssoc21, level2
