Repository purnima143/Kurakoo, pull requests merged in 2021-05, with the labels that each got.

#287 ask question
  client/src/components/AddAQuestion/AddAQuestion.css
  client/src/components/AddAQuestion/AddAQuestion.js
  client/src/components/navbar/Navbar.js
Labels: gssoc21, level2

#294 removed some bugs
  client/src/components/NotFound/NotFound.css
  client/src/components/NotFound/NotFound.js
  client/src/components/feed/feed.css
  client/src/components/images/404.png
Labels: Level3, gssoc21

#270 Added dark mode in Pages accept home page
  client/src/components/AddAQuestion/AddAQuestion.css
  client/src/components/AddAQuestion/AddAQuestion.js
  client/src/components/Homepage assets/01.png
  client/src/components/Homepage assets/02.png
  client/src/components/Homepage assets/03.png
  client/src/components/Homepage assets/about.png
  client/src/components/Homepage assets/calendar.png
  client/src/components/Homepage assets/leadership.png
  client/src/components/Homepage assets/leaf1.png
  client/src/components/Homepage assets/leaf2.png
  client/src/components/Homepage assets/main.png
  client/src/components/Homepage assets/student.png
  client/src/components/NotificationPage/NotificationPage.css
  client/src/components/NotificationPage/NotificationPage.js
  client/src/components/SignIn/SignIn.css
  client/src/components/SignIn/SignIn.js
  client/src/components/SignUp/SignUp.css
  client/src/components/SignUp/SignUp.js
  client/src/components/feed/feed.css
  client/src/components/feed/feed.js
Labels: Level3, gssoc21

#296 answer modal
  client/src/App.js
  client/src/components/Answer/Answer.js
  client/src/components/Answer/svgs/closesvg.svg
  client/src/components/Answer/svgs/linksvg.svg
  client/src/components/feed/feedComponent.js
  client/src/components/feedpage/FeedPage.js
  client/src/components/navbar/Navbar.js
Labels: gssoc21, level2

#297 Update README.md
  README.md
Labels: gssoc21, level0

#301 too many bugs
  client/src/components/AddAQuestion/AddAQuestion.css
  client/src/components/AddAQuestion/AddAQuestion.js
  client/src/components/NotificationPage/NotificationPage.js
  client/src/components/feed/feed.js
Labels: gssoc21, level2

#298 added search feature
  server/API DOCS/GET.md
  server/src/controllers/questions.controller.js
  server/src/routes/questions.routes.js
Labels: gssoc21, level2

#306 show/hide password
  client/package-lock.json
  client/package.json
  client/src/components/SignIn/SignIn.css
  client/src/components/SignIn/SignIn.js
  client/src/components/SignUp/SignUp.css
  client/src/components/SignUp/SignUp.js
  client/src/hooks/usePasswordToggle.js
  client/src/index.js
Labels: gssoc21, level2

#323 flip cards
  client/src/components/Team/team.css
  client/src/components/Team/team.jsx
Labels: gssoc21, level2

#318 UserEdit Screen
  client/src/App.js
  client/src/components/SignUp/SignUp.css
  client/src/components/UserEditScreen/UserEdit.js
Labels: Level3, gssoc21

#317 admin endpoints
  server/src/common-middleware/admin.js
  server/src/controllers/auth.controller.js
  server/src/models/user.model.js
Labels: gssoc21, level2

#327 Added admin Routes and Controllers for users, answers and questions
  package-lock.json
  package.json
  server/src/common-middleware/admin.js
  server/src/controllers/admin.controller.js
  server/src/routes/admin.routes.js
  server/src/routes/root.js
Labels: Level3, gssoc21

#332 added fetch by id endpoints
  server/src/controllers/admin.controller.js
  server/src/routes/admin.routes.js
Labels: Level3, gssoc21

#333 social sidebar
  client/src/components/Homepage-UI/Homepage.css
  client/src/components/Homepage-UI/homepage1.jsx
Labels: gssoc21, level2

#329 backend: added feature and fix questions
  server/API DOCS/DELETE.md
  server/API DOCS/GET.md
  server/package.json
  server/src/controllers/questions.controller.js
  server/src/controllers/space.controller.js
  server/src/routes/spaces.routes.js
Labels: Level3, gssoc21

#341 Search answer based on different parameters (backend)
  server/src/controllers/answers.controller.js
  server/src/models/answers.model.js
  server/src/routes/answers.routes.js
Labels: Level3, gssoc21

#339 Amin: Userlist
  client/src/App.js
  client/src/components/Admin_userlist/admin_userlist.js
Labels: Level3, gssoc21

#337 delete endpoints added
  server/src/controllers/admin.controller.js
  server/src/routes/admin.routes.js
Labels: Level3, gssoc21

#340 Get upvoted answers (backend)
  server/src/controllers/answers.controller.js
  server/src/routes/answers.routes.js
Labels: gssoc21, level2

#350 Comment (backend)
  server/src/controllers/comments.controller.js
  server/src/models/comments.model.js
  server/src/routes/comments.routes.js
  server/src/routes/root.js
Labels: Level3, gssoc21

#343 User's questions and answer endpoints
  server/src/controllers/user.controller.js
  server/src/routes/root.js
  server/src/routes/user.routes.js
Labels: gssoc21, level2

#349 admin user update
  server/src/controllers/admin.controller.js
  server/src/routes/admin.routes.js
Labels: gssoc21, level2

#353 added bookmark to questions
  server/src/controllers/questions.controller.js
  server/src/routes/questions.routes.js
Labels: Level3, gssoc21

#352 Delete+update comment (backend)
  server/src/controllers/comments.controller.js
  server/src/routes/comments.routes.js
Labels: Level3, gssoc21

#356 updated string
  server/src/index.js
Labels: gssoc21, level0

#357 added admin signup
  server/src/controllers/admin/admin.controller.js
  server/src/controllers/auth.controller.js
  server/src/models/user.model.js
  server/src/routes/admin.routes.js
Labels: Level3, gssoc21

#360 Get comments by various criteria(backend)
  server/src/controllers/comments.controller.js
  server/src/routes/comments.routes.js
Labels: Level3, gssoc21

#368 packages
  server/package.json
  server/src/index.js
Labels: Level3, gssoc21

#366 added admin signin
  server/src/controllers/admin/admin.controller.js
  server/src/routes/admin/admin.routes.js
Labels: Level3, gssoc21

#365 api docs added for admin, user and comments
  server/API DOCS/DELETE.md
  server/API DOCS/GET.md
  server/API DOCS/POST.md
  server/API DOCS/PUT.md
  server/src/controllers/admin/admin.controller.js
Labels: gssoc21, level2

#369 chatbot
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Chatbot/chatbot.js
Labels: Level3, gssoc21

#374 aboutus
  client/src/components/aboutus/aboutus.css
  client/src/components/aboutus/aboutus.js
Labels: Level3, gssoc21

#373 alert added
  client/src/components/Homepage-UI/homepage1.jsx
Labels: gssoc21, level2

#381 added admin-signout
  server/src/common-middleware/admin.js
  server/src/common-middleware/common-middleware.js
  server/src/controllers/admin/admin.controller.js
  server/src/routes/admin/admin.routes.js
Labels: gssoc21, level2

#372 added sound to chatbot
  client/src/components/Chatbot/chatbot.js
Labels: gssoc21

#393 timer
  client/package-lock.json
  client/package.json
  client/src/components/Clock/clock.css
  client/src/components/Clock/clock.js
  client/src/components/Homepage-UI/Homepage.css
  client/src/components/Homepage-UI/homepage1.jsx
  client/src/index.js
Labels: Level3, gssoc21

#394 removed bugs from the admin backend
  server/src/common-middleware/common-middleware.js
  server/src/controllers/admin/admin.controller.js
  server/src/routes/admin/admin.routes.js
  server/src/routes/answers.routes.js
  server/src/routes/auth.routes.js
  server/src/routes/comments.routes.js
  server/src/routes/questions.routes.js
  server/src/routes/root.js
  server/src/routes/spaces.routes.js
  server/src/routes/user.routes.js
Labels: gssoc21, level2

#392 added getBookmark
  server/src/controllers/questions.controller.js
  server/src/models/questions.models.js
  server/src/routes/questions.routes.js
Labels: Level3, gssoc21

#395 added bookmark page
  client/src/App.js
  client/src/components/bookmarkPage/bookmarkPage.js
  client/src/components/feed/feedComponent.js
Labels: Level3, gssoc21

#398 Added Popup comments , shown the like and dislike buttons, changed the answer button position
  client/src/components/feed/feedComponent.css
  client/src/components/feed/feedComponent.js
Labels: Level3, gssoc21

#400 Upvote+downvote question (backend)
  server/src/controllers/questions.controller.js
  server/src/models/questions.models.js
  server/src/models/user.model.js
  server/src/routes/questions.routes.js
Labels: Level3, gssoc21

#403 Update README.md
  README.md
Labels: gssoc21, level0

#404 automatic signup mail
  package-lock.json
  package.json
  server/src/controllers/auth.controller.js
  server/src/routes/auth.routes.js
  server/src/utility/signup-mail.js
Labels: Level3, gssoc21

#407 a small bug
  client/src/components/feed/feedComponent.js
Labels: gssoc21, level0

#409 added admin-mail
  server/src/controllers/admin/admin.controller.js
  server/src/controllers/auth.controller.js
  server/src/utility/signup-mail-admin.js
  server/src/utility/signup-mail-user.js
Labels: Level3, gssoc21

#411 added routes to fetch upvoted entities
  server/package.json
  server/src/controllers/answers.controller.js
  server/src/controllers/questions.controller.js
  server/src/routes/answers.routes.js
  server/src/routes/questions.routes.js
Labels: Level3, gssoc21

#415 comment upvote/downvote added
  server/src/controllers/comments.controller.js
  server/src/models/comments.model.js
  server/src/models/user.model.js
  server/src/routes/comments.routes.js
Labels: Level3, gssoc21

#417 Redux Middleware Updation
  client/src/store/index.js
  package-lock.json
  server/package.json
Labels: gssoc21, level2

#412 added getAnswerStats route
  server/src/controllers/answers.controller.js
  server/src/routes/answers.routes.js
Labels: gssoc21, level2

#413 added getQuestionStats route
  server/src/controllers/questions.controller.js
  server/src/routes/questions.routes.js
Labels: gssoc21, level2

#420 designed team page using aos
  client/package-lock.json
  client/package.json
  client/src/components/Team/team.css
  client/src/components/Team/team.jsx
Labels: Level3, gssoc21

#424 update API docs
  server/API DOCS/DELETE.md
  server/API DOCS/GET.md
  server/API DOCS/PATCH.md
Labels: gssoc21, level1

#423 added .env.example
  server/src/.env.example
  server/src/utility/signup-mail-admin.js
  server/src/utility/signup-mail-user.js
Labels: gssoc21, level2

#434 designed user edit page
  client/src/components/UserEditScreen/UserEdit.css
  client/src/components/UserEditScreen/UserEdit.js
Labels: Level3, gssoc21

#433 action and reducer for fetching users and erroe fixed
  client/package-lock.json
  client/src/actions/constants.js
  client/src/actions/user.actions.js
  client/src/reducers/user.reducers.js
  client/src/store/index.js
  server/package.json
Labels: Level3, gssoc21

#426 Addvideo
  README.md
Labels: Level3, gssoc21

#444 Progressbar
  client/package-lock.json
  client/package.json
  client/src/components/Admin_userlist/admin_userlist.js
  client/src/components/SignUp/SignUp.js
  client/src/components/UserEditScreen/UserEdit.js
Labels: gssoc21, level2

#439 admin user update action and reducer
  client/src/actions/constants.js
  client/src/actions/user.actions.js
  client/src/reducers/user.reducers.js
  client/src/store/index.js
Labels: Level3, gssoc21

#431 updated docs
  README.md
  server/API DOCS/PATCH.md
  server/API DOCS/POST.md
  server/src/controllers/questions.controller.js
Labels: gssoc21, level2

#451 added morgan and removed warings
  README.md
  client/package-lock.json
  client/src/App.js
  client/src/actions/user.actions.js
  client/src/components/Admin_UserUpdate/admin_userupdate.js
  client/src/components/Admin_userlist/admin_userlist.js
  client/src/components/Answer/Answer.js
  client/src/components/SignIn/SignIn.js
  client/src/components/UserEditScreen/UserEdit.js
  client/src/components/bookmarkPage/bookmarkPage.js
  client/src/components/feed/feedComponent.js
  client/src/components/profilePage/profilePage.js
  client/src/reducers/user.reducers.js
  package-lock.json
  package.json
  server/src/index.js
Labels: Level3, gssoc21

#453 mailjs file added
  server/mail.js
Labels: gssoc21, level2

#457 backend: unfollow request
  server/src/controllers/user.controller.js
  server/src/routes/auth.routes.js
Labels: gssoc21, level2

#459 Get+create notification
  server/API DOCS/GET.md
  server/src/controllers/answers.controller.js
  server/src/controllers/comments.controller.js
  server/src/controllers/notification.controller.js
  server/src/models/notification.model.js
  server/src/routes/notification.routes.js
Labels: Level3, gssoc21

#461 downvote notification
  server/src/controllers/answers.controller.js
  server/src/controllers/comments.controller.js
  server/src/controllers/questions.controller.js
Labels: gssoc21, level2

#458 Notification feature
  server/API DOCS/GET.md
  server/src/controllers/notification.controller.js
  server/src/routes/notification.routes.js
  server/src/routes/root.js
Labels: Level3, gssoc21

#450 designed user list and its responsive too
  client/src/components/Admin_userlist/admin_userlist.css
  client/src/components/Admin_userlist/admin_userlist.js
Labels: gssoc21, level2

#465 Edituser
  client/src/components/Admin_UserUpdate/adminScreen.css
  client/src/components/Admin_UserUpdate/admin_userupdate.js
Labels: gssoc21, level2

#469 User is able to follow space
  server/src/controllers/user.controller.js
  server/src/index.js
  server/src/models/spaces.models.js
  server/src/routes/auth.routes.js
Labels: Level3, gssoc21

#476 various aos features
  client/src/components/AddAQuestion/AddAQuestion.js
  client/src/components/Admin_UserUpdate/admin_userupdate.js
  client/src/components/Admin_userlist/admin_userlist.js
  client/src/components/Homepage-UI/homepage1.jsx
  client/src/components/SignIn/SignIn.js
  client/src/components/Team/team.jsx
  client/src/components/UserEditScreen/UserEdit.js
  client/src/components/aboutus/aboutus.js
Labels: Level3, gssoc21

#473 action and reducers to fetch answers
  client/src/actions/answer.action.js
  client/src/actions/constants.js
  client/src/components/Admin_userlist/admin_userlist.js
  client/src/reducers/answer.reducer.js
  client/src/store/index.js
Labels: gssoc21

#480 Add checks
  server/API DOCS/GET.md
  server/API DOCS/POST.md
  server/src/controllers/answers.controller.js
  server/src/controllers/comments.controller.js
  server/src/controllers/questions.controller.js
Labels: Level3, gssoc21

#474 question fetch action and reducer
  client/src/actions/constants.js
  client/src/actions/question.action.js
  client/src/components/Admin_userlist/admin_userlist.js
  client/src/reducers/question.reducer.js
  client/src/store/index.js
Labels: gssoc21

#475 comments fetch action and reducer
  client/src/actions/comment.action.js
  client/src/actions/constants.js
  client/src/components/Admin_userlist/admin_userlist.js
  client/src/reducers/comment.reducer.js
  client/src/store/index.js
Labels: gssoc21

#478 unfollow space
  server/src/controllers/user.controller.js
  server/src/routes/auth.routes.js
Labels: Level3, gssoc21

#488 added github action
  .github/workflows/automessage_on_prs.yml
Labels: gssoc21, level2

#507 Git Action
  .github/workflows/labeler.yml
Labels: Level3, gssoc21

#495 answerUpdate action and reducers
  client/src/actions/answer.action.js
  client/src/actions/constants.js
  client/src/reducers/answer.reducer.js
  client/src/store/index.js
Labels: Level3, gssoc21

#501 commentupdate action and reducer
  client/src/actions/comment.action.js
  client/src/actions/constants.js
  client/src/reducers/comment.reducer.js
  client/src/store/index.js
Labels: Level3, gssoc21

#497 QuestionUpdate action and reducers
  client/src/actions/constants.js
  client/src/actions/question.action.js
  client/src/reducers/answer.reducer.js
  client/src/reducers/question.reducer.js
  client/src/store/index.js
Labels: Level3, gssoc21

#505 bookmark page
  client/src/components/bookmarkPage/bookmark.css
  client/src/components/bookmarkPage/bookmarkPage.js
Labels: gssoc21, level2

#503 validations
  client/src/components/Admin_UserUpdate/admin_userupdate.js
  client/src/components/UserEditScreen/UserEdit.js
Labels: Level3, gssoc21

#498 added xss removed all warnings and also made some styling changes
  client/src/components/Admin_UserUpdate/admin_userupdate.js
  client/src/components/Admin_userlist/admin_userlist.js
  client/src/components/Homepage-UI/Homepage.css
  client/src/components/UserEditScreen/UserEdit.css
  server/package.json
  server/src/index.js
Labels: gssoc21, level1

#509 Downvoteredux
  client/src/actions/constants.js
  client/src/actions/downvote.action.js
  client/src/reducers/downvote.reducer.js
  client/src/store/index.js
Labels: gssoc21

#502 readme updated
  README.md
  server/.env.example
Labels: gssoc21, level1

#510 added docs
  server/API DOCS/PUT.md
Labels: gssoc21, level2

#506 Changes and fixes on the Front-end homepage
  client/package-lock.json
  client/src/components/Footer/footer.css
  client/src/components/Homepage-UI/Homepage.css
  client/src/components/homepage/homepage.css
Labels: gssoc21, level2

#514 install dependencies for the test
  package-lock.json
  package.json
  server/package.json
  server/src/config/test.json
  server/src/index.js
  server/src/test/index.js
Labels: gssoc21, level2

#513 related questions feature
  server/src/controllers/questions.controller.js
Labels: gssoc21, level2

#512 Get questions of users you follow
  server/API DOCS/GET.md
  server/src/controllers/questions.controller.js
  server/src/routes/questions.routes.js
Labels: Level3, gssoc21

#516 additional fields to user model
  server/src/controllers/auth.controller.js
  server/src/controllers/comments.controller.js
  server/src/index.js
  server/src/models/user.model.js
Labels: gssoc21, level2

#517 code: Unit testing for the signup
  server/src/index.js
  server/src/test/signup.js
Labels: Level3, gssoc21

#518 View profile
  server/API DOCS/GET.md
  server/API DOCS/POST.md
  server/src/controllers/user.controller.js
  server/src/index.js
  server/src/routes/auth.routes.js
Labels: Level3, gssoc21

#522 update readme
  README.md
Labels: Level3, gssoc21

#520 Unit testing
  server/src/index.js
  server/src/test/signup.js
Labels: gssoc21, level2
