Repository purnima143/Kurakoo, pull requests merged in 2021-04, with the labels that each got.

#88 Added the image of Main feed page(Post card for asking questions) #4
  assets/Main feed page(Post card for asking questions).png
Labels: design, gssoc21, level2

#142 prettierrc.json added
  .prettierrc.json
Labels: gssoc21, level0

#151 user is able to add questions to database
  server/src/common-middleware/middleware.js
  server/src/controllers/questions.controller.js
  server/src/models/questions.models.js
  server/src/routes/questions.routes.js
  server/src/routes/root.js
Labels: Level3, backend, gssoc21

#152 updated readme
  README.md
  assets/backend/npm_start.png
  assets/backend/signin_postman.png
  assets/backend/signup_postman.png
  assets/backend/wrong_id.png
Labels: documentation, gssoc21, level0

#156 added navbar & removed warnings
  client/src/Component/NotificationPage/NotificationPage.js
  client/src/Component/navbar/Navbar.js
  client/src/components/feed.js
Labels: gssoc21, level2

#157 Update user
  server/src/controllers/auth.controller.js
  server/src/routes/auth.routes.js
  server/src/validators/auth.validator.js
Labels: gssoc21, level2

#158 Preloader Added
  client/package-lock.json
  client/src/App.js
  client/src/Component/Preloader/KURKOO logo.png
  client/src/Component/Preloader/Preloader.css
  client/src/Component/Preloader/Preloader.jsx
  package-lock.json
  package.json
Labels: Level3, gssoc21

#166 corrected spelling
  client/src/Component/Preloader/Preloader.jsx
Labels: gssoc21, level0

#167 issue#113 about us page and contributor section
  client/src/App.js
  client/src/Component/aboutus/aboutus.css
  client/src/Component/aboutus/aboutus.js
  client/src/Component/homepage/homepage.css
  client/src/Component/homepage/homepage.js
Labels: gssoc21, level2

#169 added link & button
  client/src/Component/SignIn/SignIn.js
  client/src/Component/SignUp/SignUp.js
  client/src/Component/navbar/Navbar.js
Labels: gssoc21, level1

#170 updated question.model.js
  server/src/controllers/questions.controller.js
  server/src/models/questions.models.js
Labels: gssoc21, level2

#188 Scroll effect added
  client/src/App.css
Labels: gssoc21, level1

#189 user is able to answer the questions
  server/src/controllers/answers.controller.js
  server/src/controllers/questions.controller.js
  server/src/models/answers.model.js
  server/src/routes/answers.routes.js
  server/src/routes/root.js
Labels: Level3, gssoc21

#195 added notFound page
  client/src/App.js
  client/src/Component/NotFound/NotFound.css
  client/src/Component/NotFound/NotFound.js
Labels: frontend, gssoc21, level1

#194 added dropdown and ans button
  client/src/Component/navbar/NavBar.css
  client/src/Component/navbar/Navbar.js
  client/src/components/feedComponent.css
  client/src/components/feedComponent.js
Labels: gssoc21, level1

#201 confirm password
  server/src/controllers/answers.controller.js
  server/src/controllers/auth.controller.js
  server/src/controllers/questions.controller.js
  server/src/validators/auth.validator.js
Labels: gssoc21, level2

#197 Get all questions
  server/src/controllers/questions.controller.js
  server/src/routes/questions.routes.js
Labels: gssoc21, level2

#196 added reducers and components
  client/src/actions/constants.js
  client/src/reducers/auth.reducers.js
  client/src/reducers/index.js
Labels: gssoc21, level2

#146 Made Homepage Responsive
  client/src/Component/homepage/homepage.css
  client/src/Component/homepage/homepage.js
Labels: gssoc21, level2

#203 aboutus content
  client/src/Component/aboutus/aboutus.css
  client/src/Component/aboutus/aboutus.js
Labels: gssoc21, level2

#205 Edit question (backend)
  server/src/controllers/questions.controller.js
  server/src/routes/questions.routes.js
Labels: gssoc21, level2

#212 Dark Mode
  client/src/Component/homepage/homepage.css
  client/src/Component/homepage/homepage.js
Labels: Level3, gssoc21

#213 Side icon Bar added
  client/package-lock.json
  client/src/Component/homepage/homepage.css
  client/src/Component/homepage/homepage.js
Labels: Level3, gssoc21

#224 added axios
  client/package-lock.json
  client/package.json
  client/src/.env.example
  client/src/components/dummyData.js
  client/src/helpers/axios.js
Labels: gssoc21, level2

#230 footer-scrollbutton-refactor
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Component/kurakoo-logo.png
  client/src/components/AddAQuestion/AddAQuestion.css
  client/src/components/AddAQuestion/AddAQuestion.js
  client/src/components/AddAQuestion/svgs/closesvg.svg
  client/src/components/AddAQuestion/svgs/linksvg.svg
  client/src/components/Footer/footer.css
  client/src/components/Footer/footer.js
  client/src/components/NotFound/NotFound.css
  client/src/components/NotFound/NotFound.js
  client/src/components/NotificationPage/DummyData.js
  client/src/components/NotificationPage/NotficationComp.js
  client/src/components/NotificationPage/NotificationComp.css
  client/src/components/NotificationPage/NotificationPage.css
  client/src/components/NotificationPage/NotificationPage.js
  client/src/components/NotificationPage/images/Vector.png
  client/src/components/NotificationPage/images/Vector1.png
  client/src/components/NotificationPage/images/Vector2.png
  client/src/components/NotificationPage/images/Vector3.png
  client/src/components/NotificationPage/images/Vector4.png
  client/src/components/NotificationPage/images/Vector5.png
  client/src/components/NotificationPage/images/Vector6.png
  client/src/components/NotificationPage/images/Vector7.png
  client/src/components/NotificationPage/images/Vector8.png
  client/src/components/NotificationPage/sideBar.css
  client/src/components/NotificationPage/sideBar.js
  client/src/components/Preloader/KURKOO logo.png
  client/src/components/Preloader/Preloader.css
  client/src/components/Preloader/Preloader.jsx
  client/src/components/ScrollToTop/ScrollToTop.css
  client/src/components/ScrollToTop/ScrollToTop.js
  client/src/components/SignIn/SignIn.css
  client/src/components/SignIn/SignIn.js
  client/src/components/SignUp/SignUp.css
  client/src/components/SignUp/SignUp.js
  client/src/components/aboutus/aboutus.css
  client/src/components/aboutus/aboutus.js
  client/src/components/feed/dummyData.js
  client/src/components/feed/feed.css
  client/src/components/feed/feed.js
  client/src/components/feed/feedComponent.css
  client/src/components/feed/feedComponent.js
  client/src/components/feedpage/FeedPage.css
  client/src/components/feedpage/FeedPage.js
  client/src/components/homepage/homepage.css
  client/src/components/homepage/homepage.js
  client/src/components/navbar/NavBar.css
  client/src/components/navbar/Navbar.js
  client/src/components/searchbar/SearchBar.css
  client/src/components/searchbar/SearchBar.js
Labels: Level3, gssoc21

#236 added fields to the frontend
  client/src/components/SignUp/SignUp.js
Labels: gssoc21, level1

#238 Delete question {backend)
  server/src/controllers/questions.controller.js
  server/src/routes/questions.routes.js
Labels: gssoc21, level2

#237 refactor
  client/src/actions/constants.js
  client/src/components/AddAQuestion/AddAQuestion.css
  client/src/components/AddAQuestion/AddAQuestion.js
  client/src/components/Footer/footer.css
  client/src/components/Footer/footer.js
  client/src/components/NotFound/NotFound.css
  client/src/components/NotFound/NotFound.js
  client/src/components/NotificationPage/DummyData.js
  client/src/components/NotificationPage/NotficationComp.js
  client/src/components/NotificationPage/NotificationComp.css
  client/src/components/NotificationPage/NotificationPage.css
  client/src/components/NotificationPage/NotificationPage.js
  client/src/components/NotificationPage/sideBar.css
  client/src/components/NotificationPage/sideBar.js
  client/src/components/Preloader/Preloader.css
  client/src/components/Preloader/Preloader.jsx
  client/src/components/ScrollToTop/ScrollToTop.css
  client/src/components/ScrollToTop/ScrollToTop.js
  client/src/components/SignIn/SignIn.css
  client/src/components/SignIn/SignIn.js
  client/src/components/SignUp/SignUp.css
  client/src/components/SignUp/SignUp.js
  client/src/components/aboutus/aboutus.css
  client/src/components/aboutus/aboutus.js
  client/src/components/feed/dummyData.js
  client/src/components/feed/feed.css
  client/src/components/feed/feed.js
  client/src/components/feed/feedComponent.js
  client/src/components/feedpage/FeedPage.css
  client/src/components/feedpage/FeedPage.js
  client/src/components/homepage/homepage.css
  client/src/components/homepage/homepage.js
  client/src/components/navbar/NavBar.css
  client/src/components/navbar/Navbar.js
  client/src/components/searchbar/SearchBar.css
  client/src/components/searchbar/SearchBar.js
  client/src/helpers/axios.js
  client/src/reducers/auth.reducers.js
  client/src/reducers/index.js
  client/src/store/store.js
Labels: Level3, gssoc21

#241 edit answer (backend)
  server/src/controllers/answers.controller.js
  server/src/routes/answers.routes.js
Labels: gssoc21, level1

#248 Fixes #243
  README.md
Labels: gssoc21, level0

#261 resolved minor bugs
  client/src/actions/user.constants.js
  client/src/components/Homepage-UI/homepage1.jsx
Labels: gssoc21, level1

#253 Backend: Image Upload Functionality
  server/src/index.js
  server/src/routes/root.js
  server/src/routes/upload.routes.js
Labels: gssoc21, level2

#264 connected signin
  client/src/App.js
  client/src/actions/auth.actions.js
  client/src/actions/constants.js
  client/src/actions/index.js
  client/src/actions/user.actions.js
  client/src/components/SignIn/SignIn.js
  client/src/components/SignUp/SignUp.js
  client/src/helpers/axios.js
  client/src/index.js
  client/src/urlConfig.js
Labels: gssoc21, level2

#273 added custom titles
  client/package-lock.json
  client/package.json
  client/src/components/NotificationPage/NotificationPage.js
  client/src/components/SignIn/SignIn.js
  client/src/components/SignUp/SignUp.js
  client/src/components/feed/feed.js
  client/src/components/homepage/homepage.js
  client/src/helpers/Meta.js
Labels: gssoc21, level1

#283 content added to Homepage
  client/src/components/Homepage-UI/homepage1.jsx
Labels: gssoc21, level0

#276 fetch answers (backend)
  server/API DOCS/GET.md
  server/src/controllers/questions.controller.js
  server/src/routes/questions.routes.js
Labels: gssoc21, level2

#275 Delete profile (backend)
  server/API DOCS/DELETE.md
  server/src/controllers/auth.controller.js
  server/src/routes/auth.routes.js
Labels: gssoc21

#284 profile page
  client/src/App.js
  client/src/components/profile-pic.png
  client/src/components/profilePage/profilePage.css
  client/src/components/profilePage/profilePage.js
Labels: gssoc21, level2

#285 error fixed
  client/src/App.js
Labels: gssoc21, level1

#286 Backend :- Allow user to create spaces
  client/package-lock.json
  client/package.json
  server/API DOCS/POST.md
  server/src/controllers/space.controller.js
  server/src/models/spaces.models.js
  server/src/routes/root.js
  server/src/routes/spaces.routes.js
  server/src/validators/space.validator.js
Labels: Level3, gssoc21

#288 images folder added in components
  client/src/Component/AddAQuestion/AddAQuestion.js
  client/src/Component/navbar/Navbar.js
  client/src/components/AddAQuestion/AddAQuestion.js
  client/src/components/Footer/footer.js
  client/src/components/Homepage-UI/homepage1.jsx
  client/src/components/NotificationPage/sideBar.js
  client/src/components/SignIn/SignIn.js
  client/src/components/SignUp/SignUp.js
  client/src/components/aboutus/aboutus.js
  client/src/components/feed/dummyData.js
  client/src/components/homepage/homepage.js
  client/src/components/images/imgAvatar.png
  client/src/components/images/img_avatar.png
  client/src/components/images/img_avatar2.png
  client/src/components/images/kurakoo-logo.png
  client/src/components/images/profile-pic.png
  client/src/components/navbar/Navbar.js
  client/src/components/profilePage/profilePage.js
Labels: gssoc21, level1

#292 removed unnecessary changes
  client/src/App.js
Labels: gssoc21, level1
